// src/components/Menu.vue
<script setup lang="ts">
import { inject } from 'vue';
import { AppContextValue } from '../types';

const { startGame } = inject<AppContextValue>('AppContext')!
</script>

<template>
  <div className="menu">
    <div>
      <h1>Memory Card</h1>
      <button @click="startGame">Start Game</button>
    </div>
  </div>
</template>

// src/components/Menu/index.tsx
import { useAppContext } from "../../contexts/appContext";

function Menu() {
  const { startGame } = useAppContext();

  const handleClickStartGame = () => {
    startGame();
  }

  return (
    <div className="menu">
      <div>
        <h1>Memory Card</h1>
        <button onClick={handleClickStartGame}>Start Game</button>
      </div>
    </div>
  )
}

export default Menu;
