// src/components/WonGame.vue
<script setup lang="ts">
import { inject } from 'vue';
import { AppContextValue, WonGame } from '../types';

const props = defineProps<WonGame>()
const { resetGame } = inject<AppContextValue>('AppContext')!
</script>

<template>
  <div className="won">
    <div>
      <h1>You Win!</h1>
      Final Score:
      <p className="score">{{props.score}}</p>
      <button @click="resetGame">Main Menu</button>
    </div>
  </div>
</template>

// src/components/WonGame/index.tsx
import { useAppContext } from "../../contexts/appContext";
import { Game } from "../../core/entities/game";

export type WonGameProps = Extract<Game, { kind: 'won' }>

function WonGame({ score }: WonGameProps) {
  const app = useAppContext();

  return (
    <div className="won">
      <div>
        <h1>You Win!</h1>
        Final Score:
        <p className="score">{score}</p>
        <button onClick={() => app.resetGame()}>Main Menu</button>
      </div>
    </div>
  )
}

export default WonGame;
