// src/components/PlayingGame/index.tsx
import { Game } from "../../core/game";
import GameCard from "./GameCard";

export type PlayingGameProps = Extract<Game, { kind: 'playing' | 'matching' }>

function PlayingGame({ cards, score }: PlayingGameProps) {
  return (
    <div className="playing-game">
      <div className="header">
        <div className="score">
          <span className="score-label">Score</span>
          <span className="score-value">{score}</span>
        </div>
      </div>
      <div className="table">
        {cards.map(gameCard => (
          <GameCard
            key={`${gameCard.card.rank}-${gameCard.card.suit}`}
            state={gameCard.state}
            card={gameCard.card}
          />
        ))}
      </div>
    </div>
  )
}

export default PlayingGame;

// src/components/PlayingGame.vue
<script setup lang="ts">
import { PlayingOrMatchingGame } from '../types';
import GameCard from './GameCard.vue';

const props = defineProps<PlayingOrMatchingGame>()
</script>

<template>
  <div className="playing-game">
    <div className="header">
      <div className="score">
        <span className="score-label">Score</span>
        <span className="score-value">{{ props.score }}</span>
      </div>
    </div>
    <div className="table">
      <GameCard 
        v-for="gameCard in props.cards"
        :key="`${gameCard.card.rank}-${gameCard.card.suit}`" 
        :state="gameCard.state"
        :card="gameCard.card"
      />
    </div>
  </div>
</template>
